### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by dipkaap** [sandrocods/IdlixDownloader#12]
Saat run command `python3 main.py` respon yang didapatkan adalah sebagai berikut
Traceback (most recent call last):
  File "C:\Users\\IdlixDownloader\main.py", line 1, in <module>
    from src.idlixHelper import IdlixHelper, logger
  File "C:\Users\\IdlixDownloader\src\idlixHelper.py", line 10, in <module>
    import m3u8
ModuleNotFoundError: No module named 'm3u8'

**Comment by sandrocods** [comment]
bisa diinstall dulu modulenya dengan cara seperti berikut 

`pip3 install -r requirements.xtx`
