### ISSUE TITLE
Error running program

### ISSUE THREAD

**Issue by destroylord** [sandrocods/IdlixDownloader#5]
```bashTraceback (most recent call last):
  File "D:\laragon\www\IdlixDownloader\main.py", line 136, in <module>
    main()
  File "D:\laragon\www\IdlixDownloader\main.py", line 25, in main
    print(Fore.GREEN +
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\colorama\ansitowin32.py", line 205, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\colorama\ansitowin32.py", line 210, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 155-157: character maps to <undefined>
```

**Comment by destroylord** [comment]
Apakah ada ketentuan versi python? @sandrocods karna yang saya pakai versi terbaru v3.11.3
